[package]
name = "fp-core"
version = "0.1.0"
authors = ["Jason Shin <visualbbasic@gmail.com>"]
edition = "2018"
description = "A library for functional programming in Rust"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
