[package]
name = "functional-programming-jargon"
version = "0.1.0"
authors = ["Jason Shin <visualbbasic@gmail.com>"]
edition = "2018"

[dependencies]
partial_application = "0.1.0"
itertools = "0.8.0"
rats = "0.0.1"
